### PR TITLE
swift5.1 requires FoundationNetworking in order to use URLSession

### PR DESCRIPTION
**Pull request by fabianfett**
When compiling `aws-lmabda-swift` with swift5.1 one gets tons of errors like this:

```
Foundation.URLSession:2:18: note: 'URLSession' has been explicitly marked unavailable here
public typealias URLSession = AnyObject
                 ^
/src/.build/checkouts/aws-lambda-swift/Sources/AWSLambdaSwift/URLSession+Utils.swift:4:56: error: 'URLResponse' is unavailable: This type has moved to the FoundationNetworking module. Import that module to use it.
```

The rationale for this change in swift can be found here:
https://forums.swift.org/t/pitch-move-urlsession-to-new-foundationnetworking-module/14002

This pr imports FoundationNetwork in swift5.1 on Linux. Therefore it guaranties, compiling in swift5.1 on tuxOS.

### CODE REVIEW

**Comment by fabianfett** [comment]
Don't merge this yet. Sadly the runtime does not compile correctly. I'll probably set up tests first.

**Comment by tonisuter** [comment]
Hi. Thanks for the pull request. I merged this pull request and added some additional changes for Swift 5.1. It should work now. Note that you also need to update the Layer on AWS in order to test it.
